// Code generated by hertz generator.

package GateWay

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

// RegisterGateWay  customizeRegister registers customize routers.
func RegisterGateWay(r *server.Hertz) {

}
