// Code generated by hertz generator.

package dashboard

import (
	"github.com/cloudwego/hertz/pkg/app/server"
)

// RegisterDashBoard registers customize routers.
func RegisterDashBoard(r *server.Hertz) {
	//注册路由

}
